name: setup-mdk
description: setup mdk action
author: Dead Cells Core Modding

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  modcoreroot:
    description: The root of ModCore
    required: false
    default: ''
  downloadurl:
    description: The download url of ModCore
    required: false
    default: ''

# Define your outputs here.
outputs:
  modcoreroot:
    description: The root of ModCore
  mdkroot:
    description: The root of mdk

runs:
  using: node20
  main: dist/index.js
